%YAML:1.0

# 配置文件路径
config:
  root_path: "<dataset_root>/params"  # 配置文件根目录
  camera_intrinsics: "x3p_camera_10_front_right_6_mm_intrinsics.yaml"  # 相机内参
  extrinsics_backlidar_imu: "velodyne16_back_novatel_extrinsics.yaml"  # p_imu = T_imu_backliar * p_backlidar
  extrinsics_camera_backlidar: "x3p_camera_10_front_right_6_mm_to_velodyne16_back_extrinsics.yaml"  # p_backlidar = T_backlidar_camera * p_camera
  extrinsics_frontlidar_backlidar: "velodyne16_front_velodyne16_back_extrinsics.yaml"  # p_backlidar = T_backlidar_frontlidar * p_frontlidar

# 数据路径
data:
  root_path: "<dataset_root>"  # 数据根目录
  raw_image_data_folder: "raw_images"               # 原始图像数据文件夹
  semantic_data_folder: "semantic_images"           # 语义分割图像文件夹
  semantic_contours_file: "semantic_contours.txt"   # 语义轮廓文件
  raw_imu_data_file: "imu_data.txt"                 # 原始IMU数据文件
  ground_truth_data_file: "fast_lio.txt"            # 真值轨迹文件
  semantic_pointcloud_map_folder: "semantic_map"    # 语义点云地图文件夹

# 输出与调试
output:
  debug_output_path: "<output_root>/debug/visual_semantic_localization"  # 调试输出目录
  result_path: "<output_root>/results/visual_semantic_localization"      # 结果输出目录
  log_path: "<output_root>/logs/visual_semantic_localization"            # 日志目录

# IMU 参数配置
imu:
  freq: 0.01
  gravity: 9.8012
  sensor_noise_std:
    acc_noise_std_x: 9.8e-3
    acc_noise_std_y: 9.8e-3
    acc_noise_std_z: 9.8e-3
    gyro_noise_std_x: 1.9e-4
    gyro_noise_std_y: 1.9e-4
    gyro_noise_std_z: 4.8481e-5
  bias_random_walk_std:
    acc_bias_std_x: 6.6667e-7
    acc_bias_std_y: 6.6667e-7
    acc_bias_std_z: 6.6667e-7
    gyro_bias_std_x: 1.0167e-7
    gyro_bias_std_y: 1.0167e-7
    gyro_bias_std_z: 1.0167e-8
  initial_std:
    pos_init_std: 1e-2
    vel_init_std: 1e-3
    rot_init_std: 1e-2
    gyro_bias_init_std: 1e-4
    acc_bias_init_std: 1e-4
    gravity_init_std: 1e-3

# 图像处理参数配置
image:
  is_need_distortion: false
  is_need_downsample: true
  downsample_factor: 3
  # test_ekf_noise_trans: 100
  # test_ekf_noise_ang: 100
  # voxel_size: 0.5
  # image_point_cov: 100
  # state_init_cov: 1e2

semantic_measurement:
  search_max_distance: 50 # 在语义地图中的搜索范围


# # 其他可选参数（如有需要可继续扩展）
# cache:
#   enable: true
#   cache_path: "<output_root>/cache/visual_semantic_localization"

# model:
#   semantic_model_path: "<model_root>/semantic_segmentation.pth"
#   use_gpu: true

# # 运行参数
# runtime:
#   num_workers: 4
#   use_multithreading: true